apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-develop
  namespace: kubernetes-cluster-amarjitsingh02
  labels:
    app: dotnet-app-develop
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dotnet-app-develop
  template:
    metadata:
      labels:
        app: dotnet-app-develop
    spec:
      containers:
        - name: dotnet-app-develop
          image: amarcool55/i-amarjitsingh02-develop:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
           - configMapRef:
                name: app-config-develop
           - secretRef:
                name: app-secret-develop
---
apiVersion: v1
kind: Service
metadata:
  name: lb-dotnet-app-develop
  namespace: kubernetes-cluster-amarjitsingh02
spec:
  type: LoadBalancer
  selector:
    app: dotnet-app-develop
  ports:
  - port: 8009
    targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-develop
  namespace: kubernetes-cluster-amarjitsingh02
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "5"
  ui_properties_file_name: "user-interfacedev.properties"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret-develop
  namespace: kubernetes-cluster-amarjitsingh02
data:
  db_password: "UGFzc3dvcmRAMTIz"
  secret1: "VGhpcyBpcyBzZWNyZXQ="
type: Opaque